#!/bin/sh

echo "🔍 Running Spotless Check..."

./gradlew spotlessCheck --quiet

if [ $? -ne 0 ]; then
  echo "❌ Spotless Check failed. Running spotlessApply..."
  ./gradlew spotlessApply --quiet

  echo "📂 Applying changes..."
  git add .

  echo "✅ Spotless format applied. Please review the changes."
  echo "Aborting commit so you can verify."
  exit 1
fi

echo "✅ Spotless Check passed."

echo "🔍 Running Dependency Updates Check..."
./gradlew dependencyUpdates --quiet
git add report.json

echo "✅ Spotless and Dependency Updates completed."

exit 0